name: snake
description: A new Flutter project.
publish_to: 'none'
version: 0.2.0

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  cloud_firestore: ^4.8.5
  firebase_core: ^2.15.1
  firebase_auth: ^4.8.0
  google_fonts: ^2.1.0 
  fluttertoast: ^8.2.2
  flutter_colorpicker: ^1.0.3
  shared_preferences: ^2.2.0
  flutter_launcher_icons: "^0.9.0"
  flutter:
    sdk: flutter

flutter_icons:
  image_path: "icon/2.png" 
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

